### ISSUE TITLE
SQS permissions are too broad

### ISSUE THREAD

**Issue by theburningmonk** [horike37/serverless-apigateway-service-proxy#17]
Right now, the generated IAM role for SQS is using `*` for resources, should be tied down to the queue name that the user specified.

**Comment by erezrokah** [comment]
@horike37 I can work on this if no one has started (kinesis permissions are also `*`).

I think it will require passing the logical id(s) instead of the queue/stream name, so we can use intrinsic functions (thus introducing a breaking change).

Another option will be to build the ARN(s) using the data we already have (name, region, account id, etc.).

A third (not recommend) option will try to look up the logical id based on the queue/stream name and use that.

WDYT?

**Comment by theburningmonk** [comment]
I would prefer keeping queue name over logical ID because you're not constrained by having the queue in the same stack - e.g. you own the integration layer with third party and therefore the API Gateway proxy but another team owns the shared resources like queues, streams, etc.

So yeah, we'd have to construct the ARN from the queue name, maybe with `Fn::Sub` :

```javascript
'Fn::Sub': [
  'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${queueName}',
  { queueName }
]
```

that way, if the user uses intrinsic functions, everything would still work
