### ISSUE TITLE
Any plans to develop this further

### ISSUE THREAD

**Issue by ed-sparkes** [horike37/serverless-apigateway-service-proxy#2]
Hi, this is a great idea and thanks to @horike37 for initial plugin work. 

Do you have any plans to work on this any further. I think it would be a really useful plugin.

I thought maybe instead I could just create my service proxies in Terraform but its not ideal as I run Terraform before serverless to crate dependent resources. But because I want my service proxy to use a custom authorizer it makes much more sense to run as part of serverless where my custom authorizer is created. 

I have been looking into this and was in the process of extending  plugin to support S3 and custom authorizer functions when i realized i would end up copying a lot of the boilerplate for api gateway integration from the core lib and the only bit that really needs to be different to support these extra services is the Method Integration Request and Response.

Seems a shame that the core lib couldnt be extended to do this as they could re-use all that code for the gateways and just swap in the different integration request/repsonses. 

Any thoughts? 

I am happy to contribute too

Thanks, Ed

**Comment by horike37** [comment]
@ed-sparkes 

>Seems a shame that the core lib couldnt be extended to do this as they could re-use all that code >for the gateways and just swap in the different integration request/repsonses.

Thank you for providing your opinion and sorry for delay response. The core code around API Gateway has one problem, which is mixed sync and async code. I saw that caused to break unit tests(I'm one of maintainers team of the core) in the past therefore I converted sync parts into async code so that this plugin code is consistent with async. 

On the other hand, my method introduced duplicate issue.
I'm still debating what I should for maintainability.

**Comment by corydorning53** [comment]
was the ability to use a custom authorizer ever introduced? would love to use this plugin to setup a service proxy for s3 and use the same custom authorizer that is built using serverless and is used for my lambda's...

i read through the docs but wasn't clear on how this would be accomplished.
